### ISSUE TITLE
Primary dark color doesn't correspond to primary color

### ISSUE THREAD

**Issue by iBelieve** [liri-project/liri-vinyl#2]
On Papyros, the primary dark color is used for the window decorations, so it's important that the primary color corresponds with the primary color:

![green island_003](https://cloud.githubusercontent.com/assets/3230912/12040633/5b7454d4-ae30-11e5-8245-88290d4334f1.png)

I was going to submit a pull request for this, but I noticed that the primary color is being pulled from the user settings. I would suggest not doing this, and pick primary and accent colors to reflect your app's branding. The only time you should have a user-customizable style in my opinion is for a reading app with day/night mode.

**Comment by nickgermaine** [comment]
Ok thanks.  I'll use a specified theme color for this, and match the dark color to it.

**Comment by iBelieve** [comment]
There's also a little trick you can do with the theme:

```
theme: {
    primaryColor: "deepOrange"
}
```

Note how it's setting it to a named color instead of a hex like `primaryColor: Palette.colors["deepOrange]["500"]` does. When you do this, it'll pull the primaryColor from the Palette and automatically set `primaryDarkColor` to the corresponding dark color.

**Comment by nickgermaine** [comment]
Awesome!  That's a handy trick.

**Comment by nickgermaine** [comment]
I've got this fixed in local source, will be pushed soon.
