### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by ctnlaring** [liri-project/liri-vinyl#4]
Sorry. I don't have the time to retype.

http://stackoverflow.com/questions/34959486/taglib-in-a-c-qt-project-on-windows-10

**Comment by nickgermaine** [comment]
I've not yet done anything with it on Windows but I'll check it out and try to find a workaround for this.

**Comment by ctnlaring** [comment]
I get some problems with vlc

-CN

**Comment by nickgermaine** [comment]
I've sorted it all out for you: http://stackoverflow.com/questions/34959486/taglib-in-a-c-qt-project-on-windows-10/35214032#35214032

![2016-02-04 2](https://cloud.githubusercontent.com/assets/13626953/12833947/55e13f3e-cb7a-11e5-9b3a-70715abf5fa4.png)

Let me know if you have any issues with this.  Thanks
