### ISSUE TITLE
Project file messed up

### ISSUE THREAD

**Issue by rsnyman** [liri-project/liri-vinyl#5]
Basically, unless I'm compiling this on your machine, I cannot compile it. There are dozens of paths that are all specific to your computer.

For example:

```
INCLUDEPATH += /home/nickg/Qt/5.5/gcc_64/include
```

**Comment by rsnyman** [comment]
I tried to fix it, but I gave up. I have better things to do with my time :-(

**Comment by nickgermaine** [comment]
Ahh, sorry about that.  This is in the qmlprojecct file I think.  I wonder, if I remove this file from the repo, will a file be automatically generated for you when you open it in qt creator?  I'm learning as I go.

**Comment by ctnlaring** [comment]
@nickgermaine I believe it will be.

**Comment by nickgermaine** [comment]
Fixed I think.  I removed all the manual linking and it should work for Linux right now.  On windows, I think you'd just have to include the taglib library through qt creators gui.

As for Linux, there is taglib in the extra repository: https://www.archlinux.org/packages/extra/x86_64/taglib/

It's easier than installing taglib manually.  Though that's not difficult really.
